# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Local (target) database connection
    App\DB\PostgresConnection:
        arguments:
            $host: '%env(DEV_DB_HOST)%'
            $port: '%env(int:DEV_DB_PORT)%'
            $dbname: '%env(DEV_DB_NAME)%'
            $user: '%env(DEV_DB_USER)%'
            $password: '%env(DEV_DB_PASS)%'
            $timeoutSeconds: 10

    # Production (source) database connection
    App\DB\ProductionPostgresConnection:
        arguments:
            $host: '%env(PROD_DB_HOST)%'
            $port: '%env(int:PROD_DB_PORT)%'
            $dbname: '%env(PROD_DB_NAME)%'
            $user: '%env(PROD_DB_USER)%'
            $password: '%env(PROD_DB_PASS)%'
            $timeoutSeconds: 30

    # Source repository uses Production connection
    App\Repository\FeedSourceRepository:
        arguments:
            $conn: '@App\DB\ProductionPostgresConnection'

    # Target repository uses Dev connection
    App\Repository\FeedTargetRepository:
        arguments:
            $conn: '@App\DB\PostgresConnection'

    # Commands
    App\Command\:
        resource: '../src/Command/'
        tags: [ 'console.command' ]
